// Code generated by goctl. DO NOT EDIT.
package types

type UInfoResponse struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	Mobile string `json:"mobile"`
	Gender string `json:"gender"`
}

type ULoginResponse struct {
	Token   string `json:"token"`
	Message string `json:"message"`
}

type URequest struct {
	Id string `json:"id"`
}
