// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Id string `json:"id"`
}

type Response struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	Gender bool   `json:"gender"`
}
